services:
nginx:
  image: nginx:latest
  container_name: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/ssl:/etc/nginx/ssl
  ports:
    - "80:80"  # Map host port 80 to container port 80
    - "443:443"  # Map host port 443 to container port 443 (for HTTPS)
  depends_on:
    - php-app
    - wordpress
  restart: always

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./root:/var/www/html  # Mount your PHP app files
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./blog/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    restart: always

volumes:
  db_data: