services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./root:/var/www/html/app  # Mount your PHP app
      - ./blog/wp-content:/var/www/html/blog/wp-content  # Mount WordPress content
    ports:
      - "8000:80"
    depends_on:
      - php-app
      - wordpress
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl:/etc/nginx/ssl
    entrypoint: /bin/sh -c "trap exit TERM; while :; do sleep 2073600; done"
    restart: always

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./root:/var/www/html
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./blog/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress
    restart: always

volumes:
  db_data: